#!/usr/bin/env node
// generated by npm, please don't touch!
var dep = require('path').join(__dirname, "./../.npm/connect/1.4.1/node_modules")
var depMet = require.paths.indexOf(dep) !== -1
var from = "./../.npm/connect/1.4.1/package/index"

if (!depMet) require.paths.unshift(dep)
module.exports = require(from)

if (!depMet) {
  var i = require.paths.indexOf(dep)
  if (i !== -1) require.paths.splice(i, 1)
}
